# DNN for GW Hyperparameter Estimation

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from tensorflow import keras

In [2]:
waveforms = pd.read_csv('waveforms_with_paraName.csv')

In [3]:
waveforms.head()

Unnamed: 0             0             1             2             3  \
0           0  4.962836e-19  6.078202e-19  7.159990e-19  8.154175e-19   
1           1 -5.954363e-19 -5.906020e-19 -5.696043e-19 -5.352516e-19   
2           2 -5.553868e-19 -5.302041e-19 -4.877696e-19 -4.529003e-19   
3           3  1.542632e-19  1.702432e-20 -1.224389e-19 -2.601323e-19   
4           4  8.523908e-19  8.153931e-19  7.941967e-19  7.514200e-19   

              4             5             6             7             8  ...  \
0  9.103152e-19  1.006408e-18  1.083178e-18  1.156326e-18  1.210587e-18  ...   
1 -4.885650e-19 -4.247364e-19 -3.796092e-19 -3.350472e-19 -3.006298e-19  ...   
2 -4.218374e-19 -3.852027e-19 -3.158946e-19 -2.525576e-19 -1.931035e-19  ...   
3 -3.962478e-19 -5.333942e-19 -6.509511e-19 -7.409664e-19 -8.053906e-19  ...   
4  6.952851e-19  6.392178e-19  5.588227e-19  4.674662e-19  4.038495e-19  ...   

          18605       tc_true  phic_true    mc_true  eta_true       dl_true  \
0 -9.707775e-21  2.095587e+06      0.954  24.284086  0.082645  7.023198e+17   
1 -1.675976e-19  2.059795e+07      0.954  24.284086  0.082645  7.023198e+17   
2  9.620730e-19  1.812547e+07      0.954  24.284086  0.082645  7.023198e+17   
3 -1.047903e-18  2.276519e+07      0.954  24.284086  0.082645  7.023198e+17   
4  2.814144e-19  1.825369e+07      0.954  24.284086  0.082645  7.023198e+17   

   thetas_true  phis_true  iota_true  psi_true  
0     0.671052   1.411355   1.055404  1.613817  
1     0.658269   4.264866   1.443519  3.309646  
2     1.351814   2.773614   1.209335  2.901510  
3     1.258671   0.072278   0.707622  4.833565  
4     1.301025   5.903408   0.976030  0.315526  

[5 rows x 18616 columns]

In [4]:
waveforms.iloc[:,0]

0          0
1          1
2          2
3          3
4          4
        ... 
2995    2995
2996    2996
2997    2997
2998    2998
2999    2999
Name: Unnamed: 0, Length: 3000, dtype: int64

In [5]:
waveforms['Unnamed: 0']

0          0
1          1
2          2
3          3
4          4
        ... 
2995    2995
2996    2996
2997    2997
2998    2998
2999    2999
Name: Unnamed: 0, Length: 3000, dtype: int64

In [6]:
waveforms.drop(columns='Unnamed: 0', axis = 1, inplace = True)

In [7]:
waveforms.head()

0             1             2             3             4  \
0  4.962836e-19  6.078202e-19  7.159990e-19  8.154175e-19  9.103152e-19   
1 -5.954363e-19 -5.906020e-19 -5.696043e-19 -5.352516e-19 -4.885650e-19   
2 -5.553868e-19 -5.302041e-19 -4.877696e-19 -4.529003e-19 -4.218374e-19   
3  1.542632e-19  1.702432e-20 -1.224389e-19 -2.601323e-19 -3.962478e-19   
4  8.523908e-19  8.153931e-19  7.941967e-19  7.514200e-19  6.952851e-19   

              5             6             7             8             9  ...  \
0  1.006408e-18  1.083178e-18  1.156326e-18  1.210587e-18  1.233435e-18  ...   
1 -4.247364e-19 -3.796092e-19 -3.350472e-19 -3.006298e-19 -2.669742e-19  ...   
2 -3.852027e-19 -3.158946e-19 -2.525576e-19 -1.931035e-19 -1.255377e-19  ...   
3 -5.333942e-19 -6.509511e-19 -7.409664e-19 -8.053906e-19 -8.554588e-19  ...   
4  6.392178e-19  5.588227e-19  4.674662e-19  4.038495e-19  3.375522e-19  ...   

          18605       tc_true  phic_true    mc_true  eta_true       dl_true  \
0 -9.707775e-21  2.095587e+06      0.954  24.284086  0.082645  7.023198e+17   
1 -1.675976e-19  2.059795e+07      0.954  24.284086  0.082645  7.023198e+17   
2  9.620730e-19  1.812547e+07      0.954  24.284086  0.082645  7.023198e+17   
3 -1.047903e-18  2.276519e+07      0.954  24.284086  0.082645  7.023198e+17   
4  2.814144e-19  1.825369e+07      0.954  24.284086  0.082645  7.023198e+17   

   thetas_true  phis_true  iota_true  psi_true  
0     0.671052   1.411355   1.055404  1.613817  
1     0.658269   4.264866   1.443519  3.309646  
2     1.351814   2.773614   1.209335  2.901510  
3     1.258671   0.072278   0.707622  4.833565  
4     1.301025   5.903408   0.976030  0.315526  

[5 rows x 18615 columns]

In [8]:
waveforms.drop(columns=['phic_true','mc_true','eta_true','dl_true'], axis = 1, inplace = True) # drop unchanged parameters

In [9]:
waveforms.head()

0             1             2             3             4  \
0  4.962836e-19  6.078202e-19  7.159990e-19  8.154175e-19  9.103152e-19   
1 -5.954363e-19 -5.906020e-19 -5.696043e-19 -5.352516e-19 -4.885650e-19   
2 -5.553868e-19 -5.302041e-19 -4.877696e-19 -4.529003e-19 -4.218374e-19   
3  1.542632e-19  1.702432e-20 -1.224389e-19 -2.601323e-19 -3.962478e-19   
4  8.523908e-19  8.153931e-19  7.941967e-19  7.514200e-19  6.952851e-19   

              5             6             7             8             9  ...  \
0  1.006408e-18  1.083178e-18  1.156326e-18  1.210587e-18  1.233435e-18  ...   
1 -4.247364e-19 -3.796092e-19 -3.350472e-19 -3.006298e-19 -2.669742e-19  ...   
2 -3.852027e-19 -3.158946e-19 -2.525576e-19 -1.931035e-19 -1.255377e-19  ...   
3 -5.333942e-19 -6.509511e-19 -7.409664e-19 -8.053906e-19 -8.554588e-19  ...   
4  6.392178e-19  5.588227e-19  4.674662e-19  4.038495e-19  3.375522e-19  ...   

          18601         18602         18603         18604         18605  \
0 -8.045846e-20 -5.068457e-20 -2.452145e-20 -2.704215e-20 -9.707775e-21   
1 -3.609220e-19 -3.170464e-19 -2.625922e-19 -2.199867e-19 -1.675976e-19   
2  9.483467e-19  1.039811e-18  1.072408e-18  1.037538e-18  9.620730e-19   
3 -3.544587e-19 -5.609371e-19 -7.416180e-19 -9.060731e-19 -1.047903e-18   
4  8.739271e-19  7.918015e-19  6.591568e-19  4.970323e-19  2.814144e-19   

        tc_true  thetas_true  phis_true  iota_true  psi_true  
0  2.095587e+06     0.671052   1.411355   1.055404  1.613817  
1  2.059795e+07     0.658269   4.264866   1.443519  3.309646  
2  1.812547e+07     1.351814   2.773614   1.209335  2.901510  
3  2.276519e+07     1.258671   0.072278   0.707622  4.833565  
4  1.825369e+07     1.301025   5.903408   0.976030  0.315526  

[5 rows x 18611 columns]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(waveforms.iloc[:,0:18605], waveforms.iloc[:,-5:], test_size = 0.2, random_state = 115)

# split validation data
x_train, x_val, y_train, y_val = train_test_split(x_train.iloc[:,0:18605], y_train, test_size = 0.25, random_state = 115)

In [11]:
y_train.head()

tc_true  thetas_true  phis_true  iota_true  psi_true
2843  5.860407e+06     1.062177   4.004693   1.297916  1.340398
1181  1.385990e+07     2.234188   2.553600   0.849962  0.858338
1883  1.687134e+07     2.380436   5.604621   0.598846  1.617306
360   1.181299e+07     1.885034   1.474455   1.747477  2.114709
1836  2.024780e+07     2.473053   4.391896   2.006970  3.194625

In [12]:
x_train.head()

0             1             2             3             4  \
2843 -7.111526e-19 -7.271884e-19 -7.148747e-19 -6.899987e-19 -6.414218e-19   
1181  3.765733e-20  7.542108e-21 -6.061081e-21 -2.754501e-20 -5.048634e-20   
1883 -1.691490e-19 -2.162035e-19 -2.717940e-19 -3.502725e-19 -4.485410e-19   
360   2.554064e-19  3.232272e-19  3.825679e-19  4.171571e-19  4.560910e-19   
1836 -1.021083e-18 -1.016186e-18 -9.985500e-19 -9.910850e-19 -9.896983e-19   

                 5             6             7             8             9  \
2843 -5.651672e-19 -4.706843e-19 -3.443665e-19 -2.200953e-19 -1.049504e-19   
1181 -6.187062e-20 -9.739743e-20 -1.173401e-19 -1.227034e-19 -1.255714e-19   
1883 -5.349155e-19 -6.134755e-19 -7.035463e-19 -7.931417e-19 -8.774237e-19   
360   4.930469e-19  5.302144e-19  5.584790e-19  5.792628e-19  5.767249e-19   
1836 -9.833217e-19 -9.810322e-19 -9.672735e-19 -9.454395e-19 -9.243716e-19   

      ...         18595         18596         18597         18598  \
2843  ... -3.812079e-19 -3.420695e-19 -3.162342e-19 -2.923191e-19   
1181  ... -1.078931e-18 -1.065741e-18 -1.049115e-18 -1.034795e-18   
1883  ... -4.222667e-19 -6.078068e-19 -7.758744e-19 -9.124232e-19   
360   ... -1.136413e-19 -1.071011e-19 -1.015308e-19 -7.800247e-20   
1836  ... -2.648699e-19 -2.960646e-19 -3.258888e-19 -3.460073e-19   

             18599         18600         18601         18602         18603  \
2843 -2.527415e-19 -2.120833e-19 -1.767642e-19 -1.526109e-19 -1.232002e-19   
1181 -1.031886e-18 -1.050426e-18 -1.068607e-18 -1.089405e-18 -1.115755e-18   
1883 -9.995285e-19 -1.029583e-18 -1.045416e-18 -1.047673e-18 -9.831626e-19   
360  -6.177589e-20 -5.243019e-20 -5.117809e-20 -4.341290e-20 -3.631739e-20   
1836 -3.646821e-19 -3.706219e-19 -3.674601e-19 -3.488566e-19 -3.347521e-19   

             18604  
2843 -9.447192e-20  
1181 -1.132875e-18  
1883 -8.609643e-19  
360  -4.813746e-20  
1836 -3.361123e-19  

[5 rows x 18605 columns]

In [13]:
# standardization
# todo: try normalization or normalization then standardization, if the performance of standdardization alone is not good.
std = StandardScaler().fit(x_train)
x_train = std.transform(x_train)
x_val = std.transform(x_val)
x_test = std.transform(x_test)

x_train

array([[-0.99307986, -1.01690741, -0.99957302, ..., -0.23359637,
        -0.19627359, -0.15849272],
       [ 0.00735677, -0.0357871 , -0.0535721 , ..., -1.55608198,
        -1.59880599, -1.61421523],
       [-0.26894375, -0.33456511, -0.40822608, ..., -1.49716808,
        -1.41144545, -1.23302721],
       ...,
       [ 0.49478167,  0.53618625,  0.58664516, ...,  1.3294933 ,
         1.43150735,  1.5390786 ],
       [ 0.82184596,  0.85996357,  0.87103407, ..., -0.22820199,
        -0.38008376, -0.54186399],
       [-0.09305933, -0.15483995, -0.22273355, ...,  0.38385958,
         0.29979598,  0.2070039 ]])

In [14]:
# Stabdardization for labels
std_y = StandardScaler().fit(y_train)
y_train = std_y.transform(y_train)
y_val = std_y.transform(y_val)
y_test = std_y.transform(y_test)

y_train

array([[-1.09898665, -0.7153462 ,  0.47763943, -0.40425018, -0.95325869],
       [-0.20911348,  1.00048201, -0.32341356, -1.0650996 , -1.21954717],
       [ 0.12588258,  1.2145883 ,  1.36085391, -1.43556127, -0.80029541],
       ...,
       [ 1.15017539, -0.54597964, -1.40314978, -0.31941321,  1.2545252 ],
       [ 0.61124431, -1.15913522, -0.96099414,  1.78280723, -1.13117899],
       [-0.92124044,  0.19729341, -0.58179515,  0.69941621,  0.6112605 ]])

In [15]:
x_train = x_train.reshape(-1,18605,1)
x_val = x_val.reshape(-1,18605,1)
x_test = x_test.reshape(-1,18605,1)

x_train.shape

(1800, 18605, 1)

In [16]:
model = keras.Sequential(
    [
        #keras.Sequential([
            keras.layers.Conv1D(filters = 64, kernel_size = 16, strides = 1, padding = "causal", input_shape = (18605,1)),
            keras.layers.MaxPool1D(pool_size = 4, strides = 4, padding = "same"),
           keras.layers.ReLU(),
#        ]),
#        keras.Sequential([
            keras.layers.Conv1D(filters = 128, kernel_size = 16, strides = 1, padding = "causal"),
            keras.layers.MaxPooling1D(pool_size = 4, strides = 4, padding = "same"),
            keras.layers.ReLU(),
#        ]),
#        keras.Sequential([
            keras.layers.Conv1D(filters = 256, kernel_size = 16, strides = 1, padding = "causal"),
            keras.layers.MaxPooling1D(pool_size = 4, strides = 4, padding = "same"),
            keras.layers.ReLU(),
#        ]),
#        keras.Sequential([
            keras.layers.Conv1D(filters = 512, kernel_size = 32, strides = 1, padding = "causal"),
            keras.layers.MaxPooling1D(pool_size = 4, strides = 4, padding = "same"),
            keras.layers.ReLU(),
#        ]),
        keras.layers.Flatten(),
        keras.layers.Dense(128, activation = "relu"),
        keras.layers.Dense(64, activation = "relu"),
        keras.layers.Dense(5, activation = "relu"), # only 5 paras now
    ]
)

In [17]:
model.layers

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, 18605, 64)         1088      
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 4652, 64)          0         
_________________________________________________________________
re_lu (ReLU)                 (None, 4652, 64)          0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 4652, 128)         131200    
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 1163, 128)         0         
_________________________________________________________________
re_lu_1 (ReLU)               (None, 1163, 128)         0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 1163, 256)         5

In [19]:
model.compile(optimizer='adam', loss = 'mse', metrics=['accuracy'])

In [20]:
history=model.fit(x_train,y_train,epochs=10,batch_size=32, validation_data=(x_val,y_val))

Epoch 1/10
57/57 [==============================] - 178s 3s/step - loss: 1.8082 - accuracy: 0.2079 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 2/10
57/57 [==============================] - 176s 3s/step - loss: 0.9994 - accuracy: 0.1981 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 3/10
57/57 [==============================] - 187s 3s/step - loss: 1.0121 - accuracy: 0.1969 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 4/10
57/57 [==============================] - 208s 4s/step - loss: 0.9942 - accuracy: 0.2035 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 5/10
57/57 [==============================] - 204s 4s/step - loss: 0.9903 - accuracy: 0.2112 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 6/10
57/57 [==============================] - 208s 4s/step - loss: 1.0016 - accuracy: 0.1979 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 7/10
57/57 [==============================] - 190s 3s/step - loss: 1.0071 - accuracy: 0.2065 - val_loss: 1.0146 - val_accuracy: 0.2250
Epoch 8/10
57

In [21]:
x_train.shape, x_val.shape, y_train.shape, y_val.shape

((1800, 18605, 1), (600, 18605, 1), (1800, 5), (600, 5))

In [22]:
y_predic = model.predict(x_test)
result = std_y.inverse_transform(y_predic)

In [23]:
print(f'Our learning result is {result}')

Our learning result is [[1.5739723e+07 1.5508004e+00 3.1394577e+00 1.5719358e+00 3.0660737e+00]
 [1.5739723e+07 1.5508004e+00 3.1394577e+00 1.5719358e+00 3.0660737e+00]
 [1.5739723e+07 1.5508004e+00 3.1394577e+00 1.5719358e+00 3.0660737e+00]
 ...
 [1.5739723e+07 1.5508004e+00 3.1394577e+00 1.5719358e+00 3.0660737e+00]
 [1.5739723e+07 1.5508004e+00 3.1394577e+00 1.5719358e+00 3.0660737e+00]
 [1.5739723e+07 1.5508004e+00 3.1394577e+00 1.5719358e+00 3.0660737e+00]]
